# Generated by Django 4.2.6 on 2023-10-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0002_cart_catrgory_menuitem_order_orderitem_delete_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='Catrgory',
            new_name='catrgory',
        ),
    ]
