# Generated by Django 4.2.6 on 2023-10-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0003_rename_catrgory_menuitem_catrgory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catrgory',
            new_name='Category',
        ),
    ]
