# Generated by Django 4.2.6 on 2023-10-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0004_rename_catrgory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='catrgory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='LittleLemonDRF.category'),
        ),
    ]
