# Generated by Django 4.2.6 on 2023-10-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0005_alter_menuitem_catrgory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='catrgory',
            new_name='category',
        ),
    ]
