# Generated by Django 4.2.6 on 2023-10-29 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0006_rename_catrgory_menuitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_crew',
            new_name='delivery_crew',
        ),
    ]
